### ISSUE TITLE
Should mapGetError return an optional, since it can return null?

### ISSUE THREAD

**Issue by adworacz** [dnjulek/vapoursynth-zig#2]
https://github.com/dnjulek/vapoursynth-zig/blob/6754135e4ddc280732368dd1830b5c450d010521/src/vapoursynth4.zig#L485-L486

Noticed this while working on a new plugin.

Thank you very much for these bindings by the way!

**Comment by dnjulek** [comment]
https://github.com/dnjulek/vapoursynth-zig/commit/6b5dfc82c74fc81de502b3c01b6fe9893f8359e6 should solve it, thanks for the report.

**Comment by adworacz** [comment]
Thanks for the quick fix!
